#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const clientDir = path.resolve(__dirname, '..', 'client', 'play.pokemonshowdown.com');
const staticDir = path.resolve(__dirname, '..', 'server', 'static');

function copyRecursive(src, dest) {
	if (!fs.existsSync(src)) return;
	const stat = fs.statSync(src);
	if (stat.isDirectory()) {
		fs.mkdirSync(dest, { recursive: true });
		for (const entry of fs.readdirSync(src)) {
			copyRecursive(path.join(src, entry), path.join(dest, entry));
		}
	} else {
		fs.copyFileSync(src, dest);
	}
}

// Copy data files (generated by build-indexes)
console.log('Copying data files...');
copyRecursive(path.join(clientDir, 'data'), path.join(staticDir, 'data'));

// Copy JS files (compiled from TypeScript)
console.log('Copying JS files...');
copyRecursive(path.join(clientDir, 'js'), path.join(staticDir, 'js'));

// Copy CSS and fonts
console.log('Copying style files...');
copyRecursive(path.join(clientDir, 'style'), path.join(staticDir, 'style'));

// Copy sound effects
console.log('Copying fx files...');
copyRecursive(path.join(clientDir, 'fx'), path.join(staticDir, 'fx'));

// Copy config
console.log('Copying config files...');
copyRecursive(path.join(clientDir, 'config'), path.join(staticDir, 'config'));

// Copy sprites
console.log('Copying sprite files...');
copyRecursive(path.join(clientDir, 'sprites'), path.join(staticDir, 'sprites'));

// Copy static assets
const staticAssets = [
	'index.html',
	'favicon.ico',
	'favicon-256.png',
	'pokemonshowdownbeta.png',
	'pokemonshowdownbeta@2x.png',
	'manifest.json',
];

console.log('Copying static assets...');
for (const asset of staticAssets) {
	const src = path.join(clientDir, asset);
	const dest = path.join(staticDir, asset);
	if (fs.existsSync(src)) {
		fs.copyFileSync(src, dest);
		console.log(`  ${asset}`);
	} else {
		console.log(`  ${asset} (not found, skipped)`);
	}
}

// Remove old overlay if it exists
const overlayPath = path.join(staticDir, 'pinkacord-overlay.js');
if (fs.existsSync(overlayPath)) {
	fs.unlinkSync(overlayPath);
	console.log('Removed old pinkacord-overlay.js');
}

console.log('Done! Client files copied to server/static/');
